/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google-callback'
import { Route as ChatConversationIdRouteImport } from './routes/_chat/conversation.$id'
import { Route as ChatDirectUserIdRouteImport } from './routes/_chat/direct.$userId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDirectUserIdRoute = ChatDirectUserIdRouteImport.update({
  id: '/direct/$userId',
  path: '/direct/$userId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/login': typeof LoginRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/conversation/$id': typeof ChatConversationIdRoute
  '/direct/$userId': typeof ChatDirectUserIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/': typeof ChatIndexRoute
  '/conversation/$id': typeof ChatConversationIdRoute
  '/direct/$userId': typeof ChatDirectUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/conversation/$id': typeof ChatConversationIdRoute
  '/_chat/direct/$userId': typeof ChatDirectUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/google-callback'
    | '/conversation/$id'
    | '/direct/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/auth/google-callback'
    | '/'
    | '/conversation/$id'
    | '/direct/$userId'
  id:
    | '__root__'
    | '/_chat'
    | '/login'
    | '/auth/google-callback'
    | '/_chat/'
    | '/_chat/conversation/$id'
    | '/_chat/direct/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/conversation/$id': {
      id: '/_chat/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/direct/$userId': {
      id: '/_chat/direct/$userId'
      path: '/direct/$userId'
      fullPath: '/direct/$userId'
      preLoaderRoute: typeof ChatDirectUserIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ChatDirectUserIdRoute: typeof ChatDirectUserIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  ChatDirectUserIdRoute: ChatDirectUserIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
